---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tv-streams.fullname" . }}
  labels:
    {{- include "tv-streams.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: 8080-tcp
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: 8443-tcp
  selector:
    {{- include "tv-streams.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
